#### 파이썬 이란
- 1990년 암스테르담의 귀도 반 로섬(Guido Van Rossum)이 개발한 인터프리터 언어
- 컴퓨터 프로그래밍 교육을 위해 많이 사용하지만, 기업의 실무를 위해서도 많이 사용하는 언어. 구글에서 만든 소프트웨어의 50%이상이 파이썬으로 작성

#### 파이썬의 특징
- 파이썬은 인간다운 언어이다
- 파이썬은 문법이 쉬워 빠르게 배울 수 있다
- 파이썬은 무료이지만 강력하다
- 파이썬은 간결하다
- 파이썬은 프로그래밍을 즐기게 해준다
- 파이썬은 개발 속도가 빠르다

#### 파이썬으로 할 수 있는 일
- 웹 개발: Django, Flask 등의 프레임워크를 사용하여 웹 애플리케이션을 개발할 수 있습니다.
- 데이터 분석: Pandas, NumPy, SciPy와 같은 라이브러리를 사용하여 데이터를 분석하고 처리할 수 있습니다.
- 머신 러닝과 인공지능: TensorFlow (저수준), PyTorch, Scikit-learn 등의 라이브러리를 활용하여 머신 러닝 모델을 구축하고 훈련시킬 수 있습니다.
#####==> 머신러닝은  scikit-learn. 딥러닝은 tensor flow, pytorch
#####==> 인공지능 > 머신러닝 > 딥러닝
- 자동화: 파이썬 스크립트를 작성하여 일상적인 작업을 자동화하고, 시스템 관리 작업을 수행할 수 있습니다.
- 게임 개발: Pygame과 같은 라이브러리를 사용하여 간단한 게임을 개발할 수 있습니다.
- 모바일 애플리케이션 개발: Kivy 또는 BeeWare와 같은 라이브러리를 사용하여 모바일 애플리케이션을 개발할 수 있습니다.
- 데스크탑 애플리케이션 개발: PyQt, Tkinter 등의 라이브러리를 활용하여 데스크탑 애플리케이션을 개발할 수 있습니다.
- 시스템 스크립팅과 네트워킹: 시스템 유틸리티를 개발하거나 네트워크 프로토콜을 구현할 수 있습니다.
- 임베디드 시스템과 하드웨어 제어: 라즈베리 파이와 같은 임베디드 시스템을 제어하고 하드웨어를 프로그래밍할 수 있습니다.
- 사이언티픽 컴퓨팅: 과학적 연산과 시뮬레이션을 위해 파이썬을 활용할 수 있습니다.
- 교육: 파이썬은 초보자에게 프로그래밍을 가르치는 데 이상적인 언어로 평가받고 있습니다.
- 파이썬의 다양한 라이브러리와 프레임워크 덕분에, 이러한 분야에서의 작업이 더욱 쉽고 효율적으로 수행될 수 있습니다.

In [1]:
# ! rlghsms colab 셀에서 Unix/Linux 셸 명령어를 실행
!python --version

Python 3.10.12

In [2]:
# % 기호는 IPython 환경 (즉, colab이 포함된 주피터 환경)에서 제공하는 매직 명령어를 사용
# 라인 매직은 단일 라인에 대해 실행되며 % 하나를 사용하고 셀 매직은 셀 전체에 적용되며 %%를 사용

# 현재 작업 폴더 확인
%pwd # 단일 라인 적용

'/content'

In [3]:
%%time
# 셀 전체 적용
# 간단한 for 루프를 사용한 계산

sum=0
for i in range(1000000):
    sum+=i
print(sum)

499999500000
CPU times: user 219 ms, sys: 0 ns, total: 219 ms
Wall time: 243 ms

#### 용어
- 식별자 : 프로그램밍 언어에서 이름을 붙일 때 사용하는 단어. 주로 변수 또는 함수 이름 등으로 사용
- 주석 : 프로그램을 설명하기 위해 사용. # 기호로 주석 처리
- 연산자 : 스스로 값이 되는 것이 아니고 값과 값 사이에 무언가 기능을 적용할 때 사용
- 자료 : 리터럴이라고 하는데 숫자이든 문자이든 어떠한 값 자체를 의미. 1, 10, "Hello"
- 키워드 : 파이썬이 만들어질 때 이미 사용하겠다고 예약해 놓는 것. False, None, True, ...
- 프로그램밍 언어에서 사용자가 이름을 정할 때 키워드는 사용할 수 없음

#### 식별자
count, user_name, _is_valid, calculate_area, Car, model, year, math 및 m 모두 유효한 식별자. 각각의 식별자는 특정한 데이터 또는 기능에 이름을 부여하여 코드 내에서 해당 데이터나 기능을 참조할 수 있게하며 코드의 가독성과 유지 보수성을 높이는 데 중요한 역할

In [4]:
def calculate_area(radius):
    return 3.14159 * radius * radius
calculate_area(11)

380.13239

In [5]:
# 변수 식별자
count=10
user_name="Alice"
_is_valid=True

# 함수 식별자
def calculate_area(radius):
    return 3.14159 * radius * radius

# 클래스 식별자
class Car:
    def __init__(self, model, year):
        self.model=model
        self.year=year

# 모듈 식별자
import math as m

 #### 식별자 기본 규칙
 - 키워드를 사용하면 안됨
 - 특수문자는 언더바 (_)만 사용
 - 숫자로 시작하면 안됨
 - 공백을 포함할 수 없음

In [6]:
import keyword
print(keyword.kwlist, '\n')
len(keyword.kwlist) # 스크립터에서는 print 함수 넣어야 출력 가능

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']

35

In [10]:
# alpha
# # break # 키워드
# alpha10
# _alpha
# # 273alpha # 숫자가 식별자 초반에 올 수 없음
# AlpHa
# ALPHA
# # has space # 식별자에 공백 들어갈 수 없음

#### Q. 주어진 문자열 리스트에서 유효한 Python 변수 이름만을 추출하여 반환하는 함수를 작성하세요

In [13]:
# identifiers=["var1","2things","variable_name", "time!"]

# Python에서 사용 불가능한 변수명:
# 1. keyword
# 2. int/float으로 시작
# 3. 공백 있음
# 4. _ 외 특수문자 사용

# 즉, Python 에서 사용 가능한 변수명은 아래의 조건을 갖춰야 하며, 함수 또한 하기 조건에 부합하는 경우 identifiers 에서 요소 추출되도록 만들어야 함
# 1. 첫 글짜가 숫자가 아니라면 통과
# 2. 특수 문자 중에서도 _ 는 사용 가능하니 _ 있는 경우도 통과


# 강사님 풀이
# isidentifier() 는 파이썬의 문자열 메서드로, 주어진 문자열이 유효한 식별자인지를 확인
# 다만, isidentifier는 키워드는 걸러주지 않음. identifier 리스트 안에 키워드가 있다면 관련 조건도 추가해줘야 함
import keyword
def valid_identifiers(identifiers):
    valid=[] # 유효한 요소를 받을 리스트 생성
    for identifier in identifiers: # identifiers에 있는 각 요소를 하나씩 뽑아서
        if identifier.isidentifier() and not keyword.iskeyword(identifier): # 만약 해당 요소가 '식별자'라면
            valid.append(identifier) # valid 리스트에 해당 요소를 추가하라
    return valid # valid 리스트를 반환하라

identifiers=["var1","2things","variable_name", "time!", "True"]
print(valid_identifiers(identifiers))

# 풀이2
# 고려는 해볼 수 있지만 문제점 있으니 주의
identifiers=["var1","2things","variable_name", "time!", "True"]

for i in identifiers:
    if i[0].isdigit() or not i.isalnum():
        identifiers.remove(i) # 제거되는 순간 인덱스가 바뀌기 때문에 주의 필요
print(identifiers)


# GPT가 만들어준 거
# def valid_python_variables(identifiers):
#     valid_identifiers = []
#     for identifier in identifiers:
#         # 첫 글자가 숫자인지 확인
#         if identifier[0].isdigit():
#             continue
#         # 숫자, 영문자, 밑줄로만 구성되어 있는지 확인
#         if all(char.isalnum() or char == '_' for char in identifier):
#             valid_identifiers.append(identifier)
#     return valid_identifiers

# identifiers = ["var1", "2things", "variable_name", "time!"]
# valid_variables = valid_python_variables(identifiers)
# print(valid_variables)

['var1', 'variable_name']

####파이썬은 snake_case와 CamelCase를 모두 사용
- itemlist: item_list itemList
- loginstatus: login_status loginStatus
- 캐멀 케이스 (대문자로 시작) 클래스
- 스네이크 케이스 (소문자로 시작) 뒤에 ()가 있다 - 함수
- 스네이크 케이스(소문자로 시작) 뒤에 ()가 없다 - 변수

In [16]:
# 연산자
a=5
b=3
c=b%a # 나머지
d=b//a # 몫
e=b/a
print(c)
print(d)
print(e)

3
0
0.6

In [18]:
a=3
b=1

if a>b:
    print(a)

3

#### 자료형
- 자료형 또는 데이터 타입이란 숫자, 문자 등과 같이 여러 종류의 데이터를 구분하기 위한 분류
- 파이썬의 자료형은 크게 숫자(numbers), 시퀀스(sequence), 매핑(mapping) 등으로 나눌 수 있다.
- 파이썬의 기본 자료형
  - 수치형
    - 정수형 : int는 정수(integer)를 나타낸다. 양의 정수와 음의 정수, 숫자 0
    - 실수형 : float는 원래 부동소수점수(floating-point number)를 가리키는데, 지금은 단순히 소수점 이하를 표현할 수 있는 수이다.
    - 복소수형 : 복소수를 complex로 나타내고 제곱하면 -1이 되는 수 i를 ‘허수(imaginary number)’라고 하는데 허수 i를 j로 표현
  - 시퀀스 : 문자열(str), 리스트(list), 튜플(tuple), 사용자 정의 클래스가 시퀀스에 속한다. for 문에서 사용할 수 있는 것들이 바로 시퀀스
    - 문자열 : 문자를 한 줄로 표현하며 문자열 인덱스를 이용해 문자열의 일부를 복사
    - 리스트 : 대괄호([ ])로 감싸 주고 각 요솟값은 쉼표(,)로 구분
    - 튜플 : 튜플은 ( )으로 둘러싸고 각 요솟값은 쉼표(,)로 구분
  - 매핑
    - 사전 : 딕셔너리(dict)는 키(key)와 값(value)의 짝으로 이뤄지는데 이런 것을 매핑
  - 집합 : 집합을 표현하는 세트(set)
  - 블린 : 참, 거짓을 표현

In [19]:
# 정수형, 실수형
i1=3
f1=3.5
print(i1)
print(f1)

3
3.5

In [24]:
# 정수 (int)
# 다른 타입의 자료형을 정수형으로 바꾸기:
print(int(True)) # bool to int
print(int(False)) # bool to int
print(int('100')) # str to int
print(int(3.14)) # float to int
# print(int('10a')) # ValueError ==> 10a는 숫자와 문자가 섞여 있어서 정수형으로 변경 불가
# print(int('True')) # ValueError ==> True는 문자열이어서 정수형으로 변경 불가

1
0
100
3

In [27]:
# 실수 (float)
# 다른 타입의 자료형을 실수형으로 바꾸기
print(float(True)) # bool to float
print(float(False)) # bool to float
print(float('100')) # str to float
print(float('3.14')) # float to float

1.0
0.0
100.0
3.14

In [28]:
# 사칙연산 : +, -, *, /, //, %, **
# 정수와 실수의 계산 결과는 실수로 나옴
a=10
b=2.3
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b) # 몫
print(a%b) # 나머지
print(a**b) # 제곱

12.3
7.7
23.0
4.347826086956522
4.0
0.8000000000000007
199.52623149688787

In [ ]:
# 문자열
# '', "" 큰 차이 없이 사용

string='문자열'
a='100'

In [30]:
a=100
b=50
print(a+b)
a='100'
b='50'
print(a+b) # 문자열끼리의 "+"는 문자 연결로 결과값 출력됨

a=int('100')
b=int('50')
print(a+b) # a,b의 문자형태의 값을 int()를 사용하여 정수형으로 바꿔 계산한 값

a=int('100')
b=float('50')
print(a+b) # a를 정수형,  b를 실수형으로 바꿔 계산함. 정수, 실수로 바뀌었으니 값은 실수형으로 출력됨

150
10050
150

In [31]:
# 사용자 입력
input('인사말을 입력하세요.') # 값을 사용자에게 직접 입력하도록 요청함

인사말을 입력하세요.안녕하세요

'안녕하세요'

In [34]:
# input  사용해서 두 가지 숫자를 입력 받아 더해주도록 코딩

a=input()
b=input()
print(a+b) # input 함수는 입력 받은 값을 string으로 처리하기 때문에 a,b 를 정수로 받아도 결과는 str 연결형태로 나옴

x=int(input())
y=int(input())
print(x+y)

1
2
12
1
2
3

In [35]:
# 두개의 정수를 입력해서 더한 결과를 출력하세요
num1 = int(input("첫 번째 숫자: "))
num2 = int(input("두 번째 숫자: "))
print(num1+num2)

첫 번째 숫자: 5
두 번째 숫자: 5
10

In [38]:
# 실수+실수 -> 실수
# Q. 3과 3.3을 입력하고 숫자 연산을 수행하여 6.3을 출력하세요

num1=float(input("첫 번째 숫자: "))
num2=float(input("두 번째 숫자: "))
print(num1+num2)

# str으로 숫자를 받으면?
num1=str(input("첫 번째 숫자: "))
num2=str(input("두 번째 숫자: "))
print(num1+num2)

첫 번째 숫자: 3
두 번째 숫자: 3.3
6.3
첫 번째 숫자: 3
두 번째 숫자: 3.3
33.3

In [39]:
# 정수+실수 -> 실수
# Q. 3과 3.3을 입력하고 숫자 연산을 수행하여 6.3을 출력하세요
num1=int(input("첫 번째 숫자: "))
num2=float(input("두 번째 숫자: "))
print(num1+num2)

첫 번째 숫자: 3
두 번째 숫자: 3.3
6.3

In [44]:
# Q. a=52. b=52.273일 때 a+b는 5252.273으로 출력되도록 a와 b를 문자열 자료형으로 변환하세요

a=52
b=52.273
# 7,8행 처럼 각 변수를 str 바꾸지 않고 바로 print에서 바꾸고 싶다면:
# print(str(a)+str(b)) # <== 처럼 해야함.
a=str(a)
b=str(b)
print(a+b)

5252.273

In [46]:
# 문자열 :  "", ''. """ """, ''' '''
# p1='python's value is great' # <== 소유격 's 와 문자열 표기 ''가 겹치면서 'python'만 문자열 표기로 들어감. 오류남
p1="python's value is great"
print(p1)

python's value is great

In [45]:
# 백슬래시 (\)는 문자열 안에서 작은 따옴표 (')를 문자열의 끝을 의미하지 않는 일반 문자로 포함시키기 위해 사용
# 이 기술을 이스케이프라고 함
p1='python\'s value is great' # <== 소유격 's 표기를 위해 \' 를 s 앞에 붙여줌
print(p1)

python's value is great

In [49]:
# \n 행 바꿈
y1="Once you study data analysis You need Python" # 한 줄로 출력
y2="Once you study data analysis\nYou need Python" # \n으로 You~ 부터 행바꿈 처리되어 출력
print(y1)
print(y2)

# \t tab
y3="Once you study data analysis\tYou need Python" # 한 탭 밀어서 출력
print(y3)

Once you study data analysis You need Python
Once you study data analysis
You need Python
Once you study data analysis	You need Python

In [61]:
# ''' ==> "트리플"이라고 부름. ''' 표기가 있는 안의 내용/형식은 그대로 유지되어 출력됨
# '''과 """ 동일함

x1='''
Once you study data analysis
You need Python
'''
x2='''Once you study data analysis
You need Python
'''
x3='''Once you study data analysis
You need Python'''

x4="""
Once you study data analysis
You need Python
"""


print(x1) # 트리플 직후의 행 비움까지 출력 (첫행, 마지막행). 총 4행
print(x2) # 총 3행
print(x3) # 트리플 직후, 직전으로 행 비움 없으므로 2행으로 출력됨
print(x4) # x1과 동일하게 출력됨 (총 4행).

Once you study data analysis
You need Python

In [62]:
a1='Python'
a2=' is easy to learn'
print(a1+a2)
print("="*23) # = 를 23번 출력하도록. str에 * 숫자가 붙으면 그 횟수만큼 해당 str이 출력됨

Python is easy to learn
=======================

In [66]:
# Q. 아래와 같이 출력할 수 있는 string을 만드세요.
# "What a wonderful world!"
# he said loudly

# 1. 바로 출력하기
print("\"What a wonderful world!\nhe said loudly")

# 2. 문자열을 변수로 만들어서 출력
str1='''
"What a wonderful world!"
he said loudly'''

print(str1)

"What a wonderful world!
he said loudly

"What a wonderful world!"
he said loudly

In [71]:
# Q. 다른 타입의 숫자 2개를 입력받아 둘 중 더 큰 수를 출력하세요.

num1=int(input("정수를 입력하세요 : "))
num2=float(input("실수를 입력하세요 : "))

if num1>num2: # 조건 1
    print(num1)
elif num1<num2: # 조건 2
    print(num2)
else: # 조건 1,2 외의 케이스는 아래처럼 출력
    print("큰 수가 없습니다")

정수를 입력하세요 : 5
실수를 입력하세요 : 5
큰 수가 없습니다

In [72]:
# 자료형 - List
# 리스트는 []로 표시하며 []안의 요소를 콤마로 구분하여 순서있게 나열

list1=[1,2,3,4,5]
list2=['a','b', 'c']
list3=[1,'a','abc',[1,2,3,4,5],['a','b','c']]
print(list1)
print(list2)
print(list3)

[1, 2, 3, 4, 5]
['a', 'b', 'c']
[1, 'a', 'abc', [1, 2, 3, 4, 5], ['a', 'b', 'c']]

In [74]:
# 인덱싱
list1=[1,2,3,4,5]
print(list1[2]) # list1의 3번째 요소 추출. ** 인덱스는 0부터 시작. 즉, 첫번째 요소의 인덱스는 0
print(list1[0:2]) # 슬라이싱. list1의 첫번째 요소부터 3번째 요소까지 추출
print(list1[:4]) # 첫번째~3번째 요소까지 추출

3
[1, 2]
[1, 2, 3, 4]

In [78]:
# 리스트 안에 있는 리스트의 특정 요소 추출 원할 경우:
# list[][] 로 추출

list3=[1,'a','abc',[1,2,3,4,5],['a','b','c']]

print(list3[3][2])
print(list3[4][0])

3
a

In [80]:
# 리스트 수정, 삭제
a=[0,1,2,3,4,5,6,7,8,9]
b=['a','b','c']

a[0]=1 # 리스트 a의 인덱스 0위치의 값을 '1'로 수정하기
print(a)

b[1]='a' # 리스트 b의 인덱스 1위치의 값을 'a'로 수정
print(b)

del a[0] # 리스트 a의 인덱스 0 위치의 값 삭제
print(a)
del b[1]
print(b)

[1, 1, 2, 3, 4, 5, 6, 7, 8, 9]
['a', 'a', 'c']
[1, 2, 3, 4, 5, 6, 7, 8, 9]
['a', 'c']

In [81]:
# 끝에서부터 인덱싱: -1
# 끝에서부터 인덱싱할 경우 가장 마지막 요소의 인덱스는 -1임
a=[0,1,2,3,4,5,6,7,8,9]
b=['a','b','c']

print(a[-2]) # 끝에서 2번째 위치의 요소 추출
print(a[-4:-1]) # 끝에서 4번째 위치의 요소에서부터 끝에서 2번째까지 추출.
# **** 슬라이싱의 경우 인덱스: 인덱스 에서 끝값은 표기된 것보다 한자리 앞까지만 출력됨
print(a[-4:]) # 끝에서 4번째에서 가장 끝까지 추출

8
[6, 7, 8]
[6, 7, 8, 9]

In [82]:
# 리스트 확장
# 리스트 추가 방법은 3가지.
# extend([추가 요소들]), append(추가 요소), insert(인덱스,추가 요소)

h=[1,2,3]
h.extend([4,5]) # 반복 가능한 객체의 모든 요소를 리스트 끝에 추가
print(h)
h.append(6) # 단일 객체를 리스트 끝에 추가
print(h)
h.insert(0,5) # insert(x,y)는 x위치에 y 값을 추가하라는 뜻
print(h)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[5, 1, 2, 3, 4, 5, 6]

Q. list1에서 다음을 수행하세요
- 33을 출력
- 82를 리스트에 추가
- 87의 인덱스 구하기 - 도전
- 인덱스 3에서 10까지의 값을 출력하고 list2에 저장한 후 내림차순 정렬하기 - 도전
- 39를 11로 변경
- [69,45,58] 출력
- 짝수 인덱스의 값으로 구성된 리스트 출력하기
- 인덱스가 가장 큰수를 삭제하기
- 인덱스 3, 5인 값으로 4칙 연산하기

list1 = [58, 45, 69, 19,  4, 87, 29, 13, 39, 15, 54, [8, 33, 11], 27, 49, 63, 98, 22, 82]

In [149]:
list1 = [58, 45, 69, 19, 4, 87, 29, 13, 39, 15, 54, [8, 33, 11], 27, 49, 63, 98, 22, 82]

# 1.33을 출력
print(list1[11][1])

# 2.82를 리스트에 추가
list1.append(82)
print(list1)

# 3. 87의 인덱스 구하기 - 도전
print(list1.index(87))

# 4. 인덱스 3에서 10까지의 값을 출력하고 list2에 저장한 후 내림차순 정렬하기 - 도전
list2=list1[3:11]
list2.sort(reverse=True)
print(list2)

# 5. 39를 11로 변경
list1[8]=11
print(list1)

# 6. [69,45,58] 출력
list3=list1[:3]
list.reverse(list3)
print(list3)
# 6번 강사님 풀이
print(list1[2::-1]) # 인덱스 2에서 처음까지 출력. [::-1]이 순서 거꾸로 출력하라는 뜻

# 7. 짝수 인덱스의 값으로 구성된 리스트 출력
even_list1=list1[::2] # ::2 ==> 1칸씩 띄어서
print(even_list1)

# 8. 인덱스가 가장 큰수를 삭제하기
list_max=list1[-1]
print(list_max)

# 9. 인덱스 3, 5인 값으로 4칙 연산하기
a=list1[3]
b=list1[5]

result_add=a+b
result_minus=a-b
result_multiply=a*b
result_divide=a/b

print(result_add)
print(result_minus)
print(result_multiply)
print(result_divide)

33
[58, 45, 69, 19, 4, 87, 29, 13, 39, 15, 54, [8, 33, 11], 27, 49, 63, 98, 22, 82, 82]
5
[87, 54, 39, 29, 19, 15, 13, 4]
[58, 45, 69, 19, 4, 87, 29, 13, 11, 15, 54, [8, 33, 11], 27, 49, 63, 98, 22, 82, 82]
[69, 45, 58]
[69, 45, 58]
[58, 69, 4, 29, 11, 54, 27, 63, 22, 82]
82
106
-68
1653
0.21839080459770116

In [157]:
list1 = [58, 45, 69, 19, 4, 87, 29, 13, 39, 15, 54, [8, 33, 11], 27, 49, 63, 98, 22, 82]

print(list1)
print(list1[::-1])
print(list1[::-2])
print(list1[7::-1]) # 7번 인덱스의 요소부터 좌측방향으로 (역방향) 끝까지 출력
print(list1[7::-2]) # 7번 인덱스의 요소부터 좌측방향으로 (역방향) 1칸씩 띄면서 끝까지 출력
print(list1[7::-3]) # 7번 인덱스의 요소부터 좌측방향으로 (역방향) 2칸씩 띄면서 끝까지 출력

[58, 45, 69, 19, 4, 87, 29, 13, 39, 15, 54, [8, 33, 11], 27, 49, 63, 98, 22, 82]
[82, 22, 98, 63, 49, 27, [8, 33, 11], 54, 15, 39, 13, 29, 87, 4, 19, 69, 45, 58]
[82, 98, 49, [8, 33, 11], 15, 13, 87, 19, 45]
[13, 29, 87, 4, 19, 69, 45, 58]
[13, 87, 19, 45]
[13, 4, 45]

#### sort 와 sorted 차이점

1. 메서드 vs 함수:
- sort(): 리스트 객체의 내장 메서드입니다. 즉, 리스트에서만 사용할 수 있습니다.
- sorted(): 내장 함수로, 어떤 반복 가능한(iterable) 객체에도 사용될 수 있습니다. 예를 들면 리스트, 튜플, 딕셔너리, 문자열 등에 사용할 수 있습니다.

2. 반환 값:
- sort(): 리스트를 원 위치에서(in-place) 정렬하고 None을 반환합니다. 따라서 원래의 리스트 자체가 변경됩니다.
- sorted(): 정렬된 새로운 리스트를 반환합니다. 원래의 객체는 변경되지 않습니다.

3. 유용성:
- sort(): 리스트에서만 작동하기 때문에 리스트만 정렬할 수 있습니다.
- sorted(): 다양한 객체를 정렬할 수 있으며 결과는 항상 리스트로 반환됩니다.

In [160]:
# sort()
my_list=[3,1,2]
my_list.sort()
print(my_list)

# sorted()
my_tuple=(3,1,2)
new_list=sorted(my_tuple)
print(my_tuple)
print(new_list)


mine=[6,2,3]
mine_rev=sorted(mine)
print(mine)
print(mine_rev)

[1, 2, 3]
(3, 1, 2)
[1, 2, 3]
[6, 2, 3]
[2, 3, 6]

In [164]:
list1=[5,6,9,7,8]
new_list1=list1.sort()
print(list1)
print(new_list1) # sort()는 리스트의 내장 함수로써 리스트를 원 위치에서 정렬하고 None을 반환.

list2=[5,6,9,7,8]
new_list2=sorted(list2)
print(list2)
print(new_list2)

[5, 6, 7, 8, 9]
None
[5, 6, 9, 7, 8]
[5, 6, 7, 8, 9]

In [167]:
list1 = [58, 45, 69, 19, 4, 87, 29, 13, 39, 15, 54, [8, 33, 11], 27, 49, 63, 98, 22, 82]
list2=list1[3:11]
l_sort=sorted(list2,reverse=True)
print(l_sort)


list3=list1[3:11]
list3.sort(reverse=True)
print(list3)

[87, 54, 39, 29, 19, 15, 13, 4]
[87, 54, 39, 29, 19, 15, 13, 4]

Task1_0425. 주어진 숫자 리스트에서 최소값과 최대값을 찾아 출력하세요.

numbers = [58, 45, 69, 19, 4, 87, 29, 13, 39, 15]

In [168]:
numbers = [58, 45, 69, 19, 4, 87, 29, 13, 39, 15]

print(max(numbers)) # 최대
print(min(numbers)) # 최소

87
4

Task2_0425. 주어진 숫자 리스트의 모든 요소의 합계와 평균을 계산하고 출력하세요

numbers = [58, 45, 69, 19, 4, 87, 29, 13, 39, 15]

In [176]:
numbers = [58, 45, 69, 19, 4, 87, 29, 13, 39, 15]

# numbers 합계 :
sum=0 # 합계 변수 생성해주고
for i in numbers: # numbers에 있는 각 요소들이
    sum+=i # sum 변수에 더해지도록

# numbers 평균값 :
average=sum/len(numbers) # 합계를 numbers 요소 개수만큼 나눠주기

print(sum)
print(average)

378
37.8

Task3_0425. 주어진 리스트에서 특정 요소(target)가 등장하는 모든 인덱스를 리스트로 만들어 출력하세요.

items = ['apple', 'banana', 'cherry', 'apple', 'cherry', 'apple']

target='apple'

In [191]:
# items에서 'apple'만 추출해서 target 이라는 변수 만들어주기
items = ['apple', 'banana', 'cherry', 'apple', 'cherry', 'apple']

target=([item for item, value in enumerate(items) if value=='apple'])
print(target)

[0, 3, 5]

Task4_0425. 주어진 리스트에서 연속해서 반복되는 요소만 제거하고, 결과 리스트를 반환하세요. 단, 처음 등장하는 요소는 유지해야 합니다.

예를 들어, ['a', 'a', 'b', 'c', 'c', 'c', 'd', 'e', 'e']가 입력되면, ['a', 'b', 'c', 'd', 'e']를 출력해야 합니다.

In [224]:
items = ['apple', 'banana', 'cherry', 'apple', 'cherry', 'apple']

# list -> set -> list 자료형 변환으로:
items_set=set(items)
# items_rev=list(items_set) # TypeError <== 이거 왜 오류나는지?
items_rev=[i for i in items_set]
print(items_rev) # 근데 set를 쓰니까 첫번째 apple이 사라짐. set에서 중복값 삭제는 뒤에서부터 아닌지...?


# for문 사용:

items_rev2=[]
for item in items:
    if item not in items_rev2:
        items_rev2.append(item)
print(items_rev2)

['banana', 'cherry', 'apple']
['apple', 'banana', 'cherry']

Task5_0425 주어진 정수 리스트와 회전 횟수 k에 대해 리스트를 오른쪽으로 k만큼 회전시킨(이동시킨) 결과를 반환하세요. k가 리스트의 길이보다 클 수 있으며, 이 경우 k를 리스트 길이로 나눈 나머지만큼 실제 회전시키면 됩니다.

예를 들어, [1, 2, 3, 4, 5]와 k=2가 주어지면, 결과는 [4, 5, 1, 2, 3]이 되어야 합니다.

In [ ]:
# 모르겠다
numbers = [58, 45, 69, 19, 4, 87, 29, 13, 39, 15]
k=2